sonar.projectKey=cloudfoundry_multiapps-cli-plugin
sonar.organization=cloudfoundry
sonar.projectName="MultiApps CLI Plugin"

# Source and test layout
sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.exclusions=\
    **/test_resources/**

# Go analysis inputs
sonar.go.coverage.reportPaths=coverage.out
sonar.go.golangci-lint.reportPaths=golangci-report.json
