// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	baseclient "github.com/cloudfoundry-incubator/multiapps-cli-plugin/clients/baseclient"
	models "github.com/cloudfoundry-incubator/multiapps-cli-plugin/clients/models"
)

// GetMtasV2Reader is a Reader for the GetMtasV2 structure.
type GetMtasV2Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetMtasV2Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetMtasV2OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, baseclient.BuildErrorResponse(response, consumer, o.formats)
	}
}

// NewGetMtasV2OK creates a GetMtasV2OK with default headers values
func NewGetMtasV2OK() *GetMtasV2OK {
	return &GetMtasV2OK{}
}

/*GetMtasV2OK handles this case with default header values.

OK
*/
type GetMtasV2OK struct {
	Payload []*models.Mta
}

func (o *GetMtasV2OK) Error() string {
	return fmt.Sprintf("[GET /api/v2/spaces/{spaceGuid}/mtas][%d] getMtasV2OK  %+v", 200, o.Payload)
}

func (o *GetMtasV2OK) GetPayload() []*models.Mta {
	return o.Payload
}

func (o *GetMtasV2OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
