// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetSharedDomainsParams creates a new GetSharedDomainsParams object
// with the default values initialized.
func NewGetSharedDomainsParams() *GetSharedDomainsParams {
	var ()
	return &GetSharedDomainsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetSharedDomainsParamsWithTimeout creates a new GetSharedDomainsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetSharedDomainsParamsWithTimeout(timeout time.Duration) *GetSharedDomainsParams {
	var ()
	return &GetSharedDomainsParams{

		timeout: timeout,
	}
}

// NewGetSharedDomainsParamsWithContext creates a new GetSharedDomainsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetSharedDomainsParamsWithContext(ctx context.Context) *GetSharedDomainsParams {
	var ()
	return &GetSharedDomainsParams{

		Context: ctx,
	}
}

// NewGetSharedDomainsParamsWithHTTPClient creates a new GetSharedDomainsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetSharedDomainsParamsWithHTTPClient(client *http.Client) *GetSharedDomainsParams {
	var ()
	return &GetSharedDomainsParams{
		HTTPClient: client,
	}
}

/*GetSharedDomainsParams contains all the parameters to send to the API endpoint
for the get shared domains operation typically these are written to a http.Request
*/
type GetSharedDomainsParams struct {

	/*Page*/
	Page *string
	/*ResultsPerPage*/
	ResultsPerPage *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get shared domains params
func (o *GetSharedDomainsParams) WithTimeout(timeout time.Duration) *GetSharedDomainsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get shared domains params
func (o *GetSharedDomainsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get shared domains params
func (o *GetSharedDomainsParams) WithContext(ctx context.Context) *GetSharedDomainsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get shared domains params
func (o *GetSharedDomainsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get shared domains params
func (o *GetSharedDomainsParams) WithHTTPClient(client *http.Client) *GetSharedDomainsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get shared domains params
func (o *GetSharedDomainsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPage adds the page to the get shared domains params
func (o *GetSharedDomainsParams) WithPage(page *string) *GetSharedDomainsParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the get shared domains params
func (o *GetSharedDomainsParams) SetPage(page *string) {
	o.Page = page
}

// WithResultsPerPage adds the resultsPerPage to the get shared domains params
func (o *GetSharedDomainsParams) WithResultsPerPage(resultsPerPage *string) *GetSharedDomainsParams {
	o.SetResultsPerPage(resultsPerPage)
	return o
}

// SetResultsPerPage adds the resultsPerPage to the get shared domains params
func (o *GetSharedDomainsParams) SetResultsPerPage(resultsPerPage *string) {
	o.ResultsPerPage = resultsPerPage
}

// WriteToRequest writes these params to a swagger request
func (o *GetSharedDomainsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Page != nil {

		// query param page
		var qrPage string
		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := qrPage
		if qPage != "" {
			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}

	}

	if o.ResultsPerPage != nil {

		// query param results-per-page
		var qrResultsPerPage string
		if o.ResultsPerPage != nil {
			qrResultsPerPage = *o.ResultsPerPage
		}
		qResultsPerPage := qrResultsPerPage
		if qResultsPerPage != "" {
			if err := r.SetQueryParam("per_page", qResultsPerPage); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
