// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetOperationActionsParams creates a new GetOperationActionsParams object
// with the default values initialized.
func NewGetOperationActionsParams() *GetOperationActionsParams {
	var ()
	return &GetOperationActionsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetOperationActionsParamsWithTimeout creates a new GetOperationActionsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetOperationActionsParamsWithTimeout(timeout time.Duration) *GetOperationActionsParams {
	var ()
	return &GetOperationActionsParams{

		timeout: timeout,
	}
}

// NewGetOperationActionsParamsWithContext creates a new GetOperationActionsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetOperationActionsParamsWithContext(ctx context.Context) *GetOperationActionsParams {
	var ()
	return &GetOperationActionsParams{

		Context: ctx,
	}
}

// NewGetOperationActionsParamsWithHTTPClient creates a new GetOperationActionsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetOperationActionsParamsWithHTTPClient(client *http.Client) *GetOperationActionsParams {
	var ()
	return &GetOperationActionsParams{
		HTTPClient: client,
	}
}

/*GetOperationActionsParams contains all the parameters to send to the API endpoint
for the get operation actions operation typically these are written to a http.Request
*/
type GetOperationActionsParams struct {

	/*OperationID*/
	OperationID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get operation actions params
func (o *GetOperationActionsParams) WithTimeout(timeout time.Duration) *GetOperationActionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get operation actions params
func (o *GetOperationActionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get operation actions params
func (o *GetOperationActionsParams) WithContext(ctx context.Context) *GetOperationActionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get operation actions params
func (o *GetOperationActionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get operation actions params
func (o *GetOperationActionsParams) WithHTTPClient(client *http.Client) *GetOperationActionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get operation actions params
func (o *GetOperationActionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOperationID adds the operationID to the get operation actions params
func (o *GetOperationActionsParams) WithOperationID(operationID string) *GetOperationActionsParams {
	o.SetOperationID(operationID)
	return o
}

// SetOperationID adds the operationId to the get operation actions params
func (o *GetOperationActionsParams) SetOperationID(operationID string) {
	o.OperationID = operationID
}

// WriteToRequest writes these params to a swagger request
func (o *GetOperationActionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param operationId
	if err := r.SetPathParam("operationId", o.OperationID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
