// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetCsrfTokenParams creates a new GetCsrfTokenParams object
// with the default values initialized.
func NewGetCsrfTokenParams() *GetCsrfTokenParams {

	return &GetCsrfTokenParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetCsrfTokenParamsWithTimeout creates a new GetCsrfTokenParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetCsrfTokenParamsWithTimeout(timeout time.Duration) *GetCsrfTokenParams {

	return &GetCsrfTokenParams{

		timeout: timeout,
	}
}

// NewGetCsrfTokenParamsWithContext creates a new GetCsrfTokenParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetCsrfTokenParamsWithContext(ctx context.Context) *GetCsrfTokenParams {

	return &GetCsrfTokenParams{

		Context: ctx,
	}
}

// NewGetCsrfTokenParamsWithHTTPClient creates a new GetCsrfTokenParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetCsrfTokenParamsWithHTTPClient(client *http.Client) *GetCsrfTokenParams {

	return &GetCsrfTokenParams{
		HTTPClient: client,
	}
}

/*GetCsrfTokenParams contains all the parameters to send to the API endpoint
for the get csrf token operation typically these are written to a http.Request
*/
type GetCsrfTokenParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get csrf token params
func (o *GetCsrfTokenParams) WithTimeout(timeout time.Duration) *GetCsrfTokenParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get csrf token params
func (o *GetCsrfTokenParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get csrf token params
func (o *GetCsrfTokenParams) WithContext(ctx context.Context) *GetCsrfTokenParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get csrf token params
func (o *GetCsrfTokenParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get csrf token params
func (o *GetCsrfTokenParams) WithHTTPClient(client *http.Client) *GetCsrfTokenParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get csrf token params
func (o *GetCsrfTokenParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetCsrfTokenParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
