// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	baseclient "github.com/cloudfoundry/multiapps-cli-plugin/clients/baseclient"
)

// GetCsrfTokenReader is a Reader for the GetCsrfToken structure.
type GetCsrfTokenReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCsrfTokenReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewGetCsrfTokenNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, baseclient.BuildErrorResponse(response, consumer, o.formats)
	}
}

// NewGetCsrfTokenNoContent creates a GetCsrfTokenNoContent with default headers values
func NewGetCsrfTokenNoContent() *GetCsrfTokenNoContent {
	return &GetCsrfTokenNoContent{}
}

/*GetCsrfTokenNoContent handles this case with default header values.

No Content
*/
type GetCsrfTokenNoContent struct {
}

func (o *GetCsrfTokenNoContent) Error() string {
	return fmt.Sprintf("[GET /csrf-token][%d] getCsrfTokenNoContent ", 204)
}

func (o *GetCsrfTokenNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
