// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetMtaOperationLogContentParams creates a new GetMtaOperationLogContentParams object
// with the default values initialized.
func NewGetMtaOperationLogContentParams() *GetMtaOperationLogContentParams {
	var ()
	return &GetMtaOperationLogContentParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetMtaOperationLogContentParamsWithTimeout creates a new GetMtaOperationLogContentParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetMtaOperationLogContentParamsWithTimeout(timeout time.Duration) *GetMtaOperationLogContentParams {
	var ()
	return &GetMtaOperationLogContentParams{

		timeout: timeout,
	}
}

// NewGetMtaOperationLogContentParamsWithContext creates a new GetMtaOperationLogContentParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetMtaOperationLogContentParamsWithContext(ctx context.Context) *GetMtaOperationLogContentParams {
	var ()
	return &GetMtaOperationLogContentParams{

		Context: ctx,
	}
}

// NewGetMtaOperationLogContentParamsWithHTTPClient creates a new GetMtaOperationLogContentParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetMtaOperationLogContentParamsWithHTTPClient(client *http.Client) *GetMtaOperationLogContentParams {
	var ()
	return &GetMtaOperationLogContentParams{
		HTTPClient: client,
	}
}

/*GetMtaOperationLogContentParams contains all the parameters to send to the API endpoint
for the get mta operation log content operation typically these are written to a http.Request
*/
type GetMtaOperationLogContentParams struct {

	/*LogID*/
	LogID string
	/*OperationID*/
	OperationID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get mta operation log content params
func (o *GetMtaOperationLogContentParams) WithTimeout(timeout time.Duration) *GetMtaOperationLogContentParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get mta operation log content params
func (o *GetMtaOperationLogContentParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get mta operation log content params
func (o *GetMtaOperationLogContentParams) WithContext(ctx context.Context) *GetMtaOperationLogContentParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get mta operation log content params
func (o *GetMtaOperationLogContentParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get mta operation log content params
func (o *GetMtaOperationLogContentParams) WithHTTPClient(client *http.Client) *GetMtaOperationLogContentParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get mta operation log content params
func (o *GetMtaOperationLogContentParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLogID adds the logID to the get mta operation log content params
func (o *GetMtaOperationLogContentParams) WithLogID(logID string) *GetMtaOperationLogContentParams {
	o.SetLogID(logID)
	return o
}

// SetLogID adds the logId to the get mta operation log content params
func (o *GetMtaOperationLogContentParams) SetLogID(logID string) {
	o.LogID = logID
}

// WithOperationID adds the operationID to the get mta operation log content params
func (o *GetMtaOperationLogContentParams) WithOperationID(operationID string) *GetMtaOperationLogContentParams {
	o.SetOperationID(operationID)
	return o
}

// SetOperationID adds the operationId to the get mta operation log content params
func (o *GetMtaOperationLogContentParams) SetOperationID(operationID string) {
	o.OperationID = operationID
}

// WriteToRequest writes these params to a swagger request
func (o *GetMtaOperationLogContentParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param logId
	if err := r.SetPathParam("logId", o.LogID); err != nil {
		return err
	}

	// path param operationId
	if err := r.SetPathParam("operationId", o.OperationID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
