// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetOperationActionsReader is a Reader for the GetOperationActions structure.
type GetOperationActionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetOperationActionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetOperationActionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetOperationActionsOK creates a GetOperationActionsOK with default headers values
func NewGetOperationActionsOK() *GetOperationActionsOK {
	return &GetOperationActionsOK{}
}

/*GetOperationActionsOK handles this case with default header values.

OK
*/
type GetOperationActionsOK struct {
	Payload []string
}

func (o *GetOperationActionsOK) Error() string {
	return fmt.Sprintf("[GET /operations/{operationId}/actions][%d] getOperationActionsOK  %+v", 200, o.Payload)
}

func (o *GetOperationActionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
