// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	baseclient "github.com/cloudfoundry/multiapps-cli-plugin/clients/baseclient"
)

// GetMtaOperationLogContentReader is a Reader for the GetMtaOperationLogContent structure.
type GetMtaOperationLogContentReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetMtaOperationLogContentReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetMtaOperationLogContentOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, baseclient.BuildErrorResponse(response, consumer, o.formats)
	}
}

// NewGetMtaOperationLogContentOK creates a GetMtaOperationLogContentOK with default headers values
func NewGetMtaOperationLogContentOK() *GetMtaOperationLogContentOK {
	return &GetMtaOperationLogContentOK{}
}

/*GetMtaOperationLogContentOK handles this case with default header values.

OK
*/
type GetMtaOperationLogContentOK struct {
	Payload string
}

func (o *GetMtaOperationLogContentOK) Error() string {
	return fmt.Sprintf("[GET /operations/{operationId}/logs/{logId}/content][%d] getMtaOperationLogContentOK  %+v", 200, o.Payload)
}

func (o *GetMtaOperationLogContentOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
