// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	baseclient "github.com/cloudfoundry-incubator/multiapps-cli-plugin/clients/baseclient"
	"github.com/cloudfoundry-incubator/multiapps-cli-plugin/clients/models"
)

// GetMtaFilesReader is a Reader for the GetMtaFiles structure.
type GetMtaFilesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetMtaFilesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetMtaFilesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, baseclient.BuildErrorResponse(response, consumer, o.formats)
	}
}

// NewGetMtaFilesOK creates a GetMtaFilesOK with default headers values
func NewGetMtaFilesOK() *GetMtaFilesOK {
	return &GetMtaFilesOK{}
}

/*GetMtaFilesOK handles this case with default header values.

OK
*/
type GetMtaFilesOK struct {
	Payload models.GetMtaFilesOKBody
}

func (o *GetMtaFilesOK) Error() string {
	return fmt.Sprintf("[GET /files][%d] getMtaFilesOK  %+v", 200, o.Payload)
}

func (o *GetMtaFilesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
