// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	baseclient "github.com/cloudfoundry/multiapps-cli-plugin/clients/baseclient"
)

// StartMtaOperationReader is a Reader for the StartMtaOperation structure.
type StartMtaOperationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *StartMtaOperationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 202:
		result := NewStartMtaOperationAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, baseclient.BuildErrorResponse(response, consumer, o.formats)
	}
}

// NewStartMtaOperationAccepted creates a StartMtaOperationAccepted with default headers values
func NewStartMtaOperationAccepted() *StartMtaOperationAccepted {
	return &StartMtaOperationAccepted{}
}

/*StartMtaOperationAccepted handles this case with default header values.

Accepted
*/
type StartMtaOperationAccepted struct {
	/*A Location header, used for transpassing between different resources

	 */
	Location strfmt.URI
}

func (o *StartMtaOperationAccepted) Error() string {
	return fmt.Sprintf("[POST /operations][%d] startMtaOperationAccepted ", 202)
}

func (o *StartMtaOperationAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header Location

	location, err := formats.Parse("uri", response.GetHeader("Location"))
	if err != nil {
		return errors.InvalidType("Location", "header", "strfmt.URI", response.GetHeader("Location"))
	}
	o.Location = *(location.(*strfmt.URI))

	return nil
}
