// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/cloudfoundry-incubator/multiapps-cli-plugin/clients/models"
)

// NewStartMtaOperationParams creates a new StartMtaOperationParams object
// with the default values initialized.
func NewStartMtaOperationParams() *StartMtaOperationParams {
	var ()
	return &StartMtaOperationParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewStartMtaOperationParamsWithTimeout creates a new StartMtaOperationParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewStartMtaOperationParamsWithTimeout(timeout time.Duration) *StartMtaOperationParams {
	var ()
	return &StartMtaOperationParams{

		timeout: timeout,
	}
}

// NewStartMtaOperationParamsWithContext creates a new StartMtaOperationParams object
// with the default values initialized, and the ability to set a context for a request
func NewStartMtaOperationParamsWithContext(ctx context.Context) *StartMtaOperationParams {
	var ()
	return &StartMtaOperationParams{

		Context: ctx,
	}
}

// NewStartMtaOperationParamsWithHTTPClient creates a new StartMtaOperationParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewStartMtaOperationParamsWithHTTPClient(client *http.Client) *StartMtaOperationParams {
	var ()
	return &StartMtaOperationParams{
		HTTPClient: client,
	}
}

/*StartMtaOperationParams contains all the parameters to send to the API endpoint
for the start mta operation operation typically these are written to a http.Request
*/
type StartMtaOperationParams struct {

	/*Operation*/
	Operation *models.Operation

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the start mta operation params
func (o *StartMtaOperationParams) WithTimeout(timeout time.Duration) *StartMtaOperationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the start mta operation params
func (o *StartMtaOperationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the start mta operation params
func (o *StartMtaOperationParams) WithContext(ctx context.Context) *StartMtaOperationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the start mta operation params
func (o *StartMtaOperationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the start mta operation params
func (o *StartMtaOperationParams) WithHTTPClient(client *http.Client) *StartMtaOperationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the start mta operation params
func (o *StartMtaOperationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOperation adds the operation to the start mta operation params
func (o *StartMtaOperationParams) WithOperation(operation *models.Operation) *StartMtaOperationParams {
	o.SetOperation(operation)
	return o
}

// SetOperation adds the operation to the start mta operation params
func (o *StartMtaOperationParams) SetOperation(operation *models.Operation) {
	o.Operation = operation
}

// WriteToRequest writes these params to a swagger request
func (o *StartMtaOperationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Operation == nil {
		o.Operation = new(models.Operation)
	}

	if err := r.SetBodyParam(o.Operation); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
