// This file was generated by counterfeiter
package fakes

import (
	"sync"

	restclient "github.com/SAP/cf-mta-plugin/clients/restclient"
)

type FakeRestClientOperations struct {}
	PurgeConfigurationStub        func(org, space string) error
	purgeConfigurationMutex       sync.RWMutex
	purgeConfigurationArgsForCall []struct {
		org   string
		space string
	}
	purgeConfigurationReturns struct {
		result1 error
	}
}

func (fake *FakeRestClientOperations) PurgeConfigurationCallCount() int {
	fake.purgeConfigurationMutex.RLock()
	defer fake.purgeConfigurationMutex.RUnlock()
	return len(fake.purgeConfigurationArgsForCall)
}

func (fake *FakeRestClientOperations) PurgeConfigurationArgsForCall(i int) (string, string) {
	fake.purgeConfigurationMutex.RLock()
	defer fake.purgeConfigurationMutex.RUnlock()
	return fake.purgeConfigurationArgsForCall[i].org, fake.purgeConfigurationArgsForCall[i].space
}

func (fake *FakeRestClientOperations) PurgeConfigurationReturns(result1 error) {
	fake.PurgeConfigurationStub = nil
	fake.purgeConfigurationReturns = struct {
		result1 error
	}{result1}
}

var _ restclient.RestClientOperations = new(FakeRestClientOperations)
