// This file was generated by counterfeiter
package fakes

import (
	"sync"

	restclient "github.com/cloudfoundry-incubator/multiapps-cli-plugin/clients/restclient"
)

type FakeRestClientOperations struct {
	PurgeConfigurationStub        func(org, space string) error
	purgeConfigurationMutex       sync.RWMutex
	purgeConfigurationArgsForCall []struct {
		org   string
		space string
	}
	purgeConfigurationReturns struct {
		result1 error
	}
}

func (fake *FakeRestClientOperations) PurgeConfiguration(org string, space string) error {
	fake.purgeConfigurationMutex.Lock()
	fake.purgeConfigurationArgsForCall = append(fake.purgeConfigurationArgsForCall, struct {
		org   string
		space string
	}{org, space})
	fake.purgeConfigurationMutex.Unlock()
	if fake.PurgeConfigurationStub != nil {
		return fake.PurgeConfigurationStub(org, space)
	} else {
		return fake.purgeConfigurationReturns.result1
	}
}
func (fake *FakeRestClientOperations) PurgeConfigurationCallCount() int {
	fake.purgeConfigurationMutex.RLock()
	defer fake.purgeConfigurationMutex.RUnlock()
	return len(fake.purgeConfigurationArgsForCall)
}

func (fake *FakeRestClientOperations) PurgeConfigurationArgsForCall(i int) (string, string) {
	fake.purgeConfigurationMutex.RLock()
	defer fake.purgeConfigurationMutex.RUnlock()
	return fake.purgeConfigurationArgsForCall[i].org, fake.purgeConfigurationArgsForCall[i].space
}

func (fake *FakeRestClientOperations) PurgeConfigurationReturns(result1 error) {
	fake.PurgeConfigurationStub = nil
	fake.purgeConfigurationReturns = struct {
		result1 error
	}{result1}
}

var _ restclient.RestClientOperations = new(FakeRestClientOperations)
