package restclient

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/SAP/cf-mta-plugin/clients/restclient/operations"
)

// Default rest HTTP client.
var Default = NewHTTPClient(nil)

// NewHTTPClient creates a new rest HTTP client.
func NewHTTPClient(formats strfmt.Registry) *Rest {
	if formats == nil {
		formats = strfmt.Default
	}
	transport := httptransport.New("example.com", "/rest/", "/rest/", []string{"http", "https"})
	return New(transport, formats)
}

// New creates a new rest client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Rest {
	cli := new(Rest)
	cli.Transport = transport

	cli.Operations = operations.New(transport, formats)

	return cli
}

// Rest is a client for rest
type Rest struct {
	Operations *operations.Client

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *Rest) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport

	c.Operations.SetTransport(transport)

}
