package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/xml"

	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/go-openapi/errors"
)

// Actions actions
// swagger:model actions
type Actions struct {
	XMLName xml.Name  `xml:"http://www.sap.com/lmsl/slp actions"`
	Actions []*Action `xml:"Action,omitempty"`
}

// Validate validates this actions
func (m Actions) Validate(formats strfmt.Registry) error {
	var res []error

	for i := 0; i < len(m.Actions); i++ {

		if swag.IsZero(m.Actions[i]) { // not required
			continue
		}

		if m.Actions[i] != nil {

			if err := m.Actions[i].Validate(formats); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
