// Code generated by go-swagger; DO NOT EDIT.

package models

type CloudFoundryPagination struct {

	Next Link `json:"next,omitempty"`

	Prev Link `json:"prev,omitempty"`

	TotalPages int64 `json:"total_pages,omitempty"`

	TotalResults int64 `json:"total_results,omitempty"`
}

type Link struct {

	Href string `json:"href,omitempty"`
}
