// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command


import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CloudFoundryResource cloud foundry resource
// swagger:model CloudFoundryResource

type CloudFoundryResourceRelationships struct {

	// organization
	Organization *CloudFoundryRelationship `json:"organization,omitempty"`
}

/* polymorph CloudFoundryResourceRelationships organization false */

// Validate validates this cloud foundry resource
func (m *CloudFoundryResourceRelationships) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *CloudFoundryResourceRelationships) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CloudFoundryResourceRelationships) UnmarshalBinary(b []byte) error {
	var res CloudFoundryResourceRelationships
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

