// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// CloudFoundryResourceEntity cloud foundry resource entity
// swagger:model CloudFoundryResource_entity

type CloudFoundryResourceEntity struct {

	// name
	Name string `json:"name,omitempty"`
}

/* polymorph CloudFoundryResource_entity name false */

// Validate validates this cloud foundry resource entity
func (m *CloudFoundryResourceEntity) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *CloudFoundryResourceEntity) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CloudFoundryResourceEntity) UnmarshalBinary(b []byte) error {
	var res CloudFoundryResourceEntity
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
