package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/xml"

	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/go-openapi/errors"
)

// Dialogs dialogs
// swagger:model dialogs
type Dialogs struct {
	XMLName xml.Name  `xml:"http://www.sap.com/lmsl/slp dialogs"`
	Dialogs []*Dialog `xml:"Dialog,omitempty"`
}

// Validate validates this dialogs
func (m Dialogs) Validate(formats strfmt.Registry) error {
	var res []error

	for i := 0; i < len(m.Dialogs); i++ {

		if swag.IsZero(m.Dialogs[i]) { // not required
			continue
		}

		if m.Dialogs[i] != nil {

			if err := m.Dialogs[i].Validate(formats); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
