package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/xml"

	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/go-openapi/errors"
)

// Files files
// swagger:model files
type Files struct {
	XMLName xml.Name `xml:"http://www.sap.com/lmsl/slp files"`
	Files   []*File  `xml:"File,omitempty"`
}

// Validate validates this files
func (m Files) Validate(formats strfmt.Registry) error {
	var res []error

	for i := 0; i < len(m.Files); i++ {

		if swag.IsZero(m.Files[i]) { // not required
			continue
		}

		if m.Files[i] != nil {

			if err := m.Files[i].Validate(formats); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
