package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/xml"

	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/go-openapi/errors"
)

// Logs logs
// swagger:model logs
type Logs struct {
	XMLName xml.Name `xml:"http://www.sap.com/lmsl/slp logs"`
	Logs    []*Log   `xml:"Log,omitempty"`
}

// Validate validates this logs
func (m Logs) Validate(formats strfmt.Registry) error {
	var res []error

	for i := 0; i < len(m.Logs); i++ {

		if swag.IsZero(m.Logs[i]) { // not required
			continue
		}

		if m.Logs[i] != nil {

			if err := m.Logs[i].Validate(formats); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
