package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/xml"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// MetaDialogs meta dialogs
// swagger:model metaDialogs
type MetaDialogs struct {
	XMLName     xml.Name `xml:"http://www.sap.com/lmsl/slp metaDialogs"`
	MetaDialogs []string `xml:"MetaDialog,omitempty"`
}

// Validate validates this meta dialogs
func (m MetaDialogs) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
