package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/xml"

	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/go-openapi/errors"
)

// Monitor monitor
// swagger:model monitor
type Monitor struct {
	XMLName xml.Name `xml:"http://www.sap.com/lmsl/slp monitor"`
	Tasks   []*Task  `xml:"Task,omitempty"`
}

// Validate validates this monitor
func (m Monitor) Validate(formats strfmt.Registry) error {
	var res []error

	for i := 0; i < len(m.Tasks); i++ {

		if swag.IsZero(m.Tasks[i]) { // not required
			continue
		}

		if m.Tasks[i] != nil {

			if err := m.Tasks[i].Validate(formats); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
