package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/xml"

	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/go-openapi/errors"
)

// Operations operations
// swagger:model operations
type Operations struct {
	XMLName    xml.Name     `xml:"ongoing-operations"`
	Operations []*Operation `xml:"ongoing-operation,omitempty"`
}

// Validate validates this operations
func (m Operations) Validate(formats strfmt.Registry) error {
	var res []error

	for i := 0; i < len(m.Operations); i++ {

		if swag.IsZero(m.Operations[i]) { // not required
			continue
		}

		if m.Operations[i] != nil {

			if err := m.Operations[i].Validate(formats); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
