package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/xml"

	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/go-openapi/errors"
)

// Processes processes
// swagger:model processes
type Processes struct {
	XMLName   xml.Name   `xml:"http://www.sap.com/lmsl/slp processes"`
	Processes []*Process `xml:"Process,omitempty"`
}

// Validate validates this processes
func (m Processes) Validate(formats strfmt.Registry) error {
	var res []error

	for i := 0; i < len(m.Processes); i++ {

		if swag.IsZero(m.Processes[i]) { // not required
			continue
		}

		if m.Processes[i] != nil {

			if err := m.Processes[i].Validate(formats); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
