package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/xml"

	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/go-openapi/errors"
)

// Properties properties
// swagger:model properties
type Properties struct {
	XMLName    xml.Name    `xml:"http://www.sap.com/lmsl/slp properties"`
	Properties []*Property `xml:"Property,omitempty"`
}

// Validate validates this properties
func (m Properties) Validate(formats strfmt.Registry) error {
	var res []error

	for i := 0; i < len(m.Properties); i++ {

		if swag.IsZero(m.Properties[i]) { // not required
			continue
		}

		if m.Properties[i] != nil {

			if err := m.Properties[i].Validate(formats); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
