package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/xml"

	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/go-openapi/errors"
)

// Services services
// swagger:model services
type Services struct {
	XMLName  xml.Name   `xml:"http://www.sap.com/lmsl/slp services"`
	Services []*Service `xml:"Service,omitempty"`
}

// Validate validates this services
func (m Services) Validate(formats strfmt.Registry) error {
	var res []error

	for i := 0; i < len(m.Services); i++ {

		if swag.IsZero(m.Services[i]) { // not required
			continue
		}

		if m.Services[i] != nil {

			if err := m.Services[i].Validate(formats); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
