package models

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
)

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// SlpLogFormat slp log format
// swagger:model slp_log_format
type SlpLogFormat struct {
	SlpLogFormatEnum

	SlpLogFormatExtensions
}

// Validate validates this slp log format
func (m *SlpLogFormat) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.SlpLogFormatEnum.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.SlpLogFormatExtensions.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
