package models

import "github.com/go-openapi/strfmt"

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// SlpTimestamp slp timestamp
// swagger:model slp_timestamp
type SlpTimestamp strfmt.DateTime

// Validate validates this slp timestamp
func (m SlpTimestamp) Validate(formats strfmt.Registry) error {
	return nil
}
