package models

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
)

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// SlpAction slp action
// swagger:model slp_action
type SlpAction struct {
	SlpActionEnum

	SlpActionExtensions
}

// Validate validates this slp action
func (m *SlpAction) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.SlpActionEnum.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.SlpActionExtensions.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
