package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetOperationParams creates a new GetOperationParams object
// with the default values initialized.
func NewGetOperationParams() *GetOperationParams {
	var ()
	return &GetOperationParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetOperationParamsWithTimeout creates a new GetOperationParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetOperationParamsWithTimeout(timeout time.Duration) *GetOperationParams {
	var ()
	return &GetOperationParams{

		timeout: timeout,
	}
}

// NewGetOperationParamsWithContext creates a new GetOperationParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetOperationParamsWithContext(ctx context.Context) *GetOperationParams {
	var ()
	return &GetOperationParams{

		Context: ctx,
	}
}

/*GetOperationParams contains all the parameters to send to the API endpoint
for the get operation operation typically these are written to a http.Request
*/
type GetOperationParams struct {

	/*ProcessID*/
	ProcessID string

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the get operation params
func (o *GetOperationParams) WithTimeout(timeout time.Duration) *GetOperationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get operation params
func (o *GetOperationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get operation params
func (o *GetOperationParams) WithContext(ctx context.Context) *GetOperationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get operation params
func (o *GetOperationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithProcessID adds the processID to the get operation params
func (o *GetOperationParams) WithProcessID(processID string) *GetOperationParams {
	o.SetProcessID(processID)
	return o
}

// SetProcessID adds the processId to the get operation params
func (o *GetOperationParams) SetProcessID(processID string) {
	o.ProcessID = processID
}

// WriteToRequest writes these params to a swagger request
func (o *GetOperationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param processId
	if err := r.SetPathParam("processId", o.ProcessID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
