package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/SAP/cf-mta-plugin/clients/models"
)

// GetOperationsReader is a Reader for the GetOperations structure.
type GetOperationsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetOperationsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetOperationsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetOperationsOK creates a GetOperationsOK with default headers values
func NewGetOperationsOK() *GetOperationsOK {
	return &GetOperationsOK{}
}

/*GetOperationsOK handles this case with default header values.

OK
*/
type GetOperationsOK struct {
	Payload models.Operations
}

func (o *GetOperationsOK) Error() string {
	return fmt.Sprintf("[GET /operations][%d] getOperationsOK  %+v", 200, o.Payload)
}

func (o *GetOperationsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
