package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/SAP/cf-mta-plugin/clients/models"
)

// CreateServiceProcessReader is a Reader for the CreateServiceProcess structure.
type CreateServiceProcessReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateServiceProcessReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCreateServiceProcessOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateServiceProcessOK creates a CreateServiceProcessOK with default headers values
func NewCreateServiceProcessOK() *CreateServiceProcessOK {
	return &CreateServiceProcessOK{}
}

/*CreateServiceProcessOK handles this case with default header values.

Created
*/
type CreateServiceProcessOK struct {
	Payload *models.Process
}

func (o *CreateServiceProcessOK) Error() string {
	return fmt.Sprintf("[POST /services/{serviceId}/processes][%d] createServiceProcessOK  %+v", 200, o.Payload)
}

func (o *CreateServiceProcessOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Process)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
