package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteServiceProcessReader is a Reader for the DeleteServiceProcess structure.
type DeleteServiceProcessReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteServiceProcessReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDeleteServiceProcessNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteServiceProcessNoContent creates a DeleteServiceProcessNoContent with default headers values
func NewDeleteServiceProcessNoContent() *DeleteServiceProcessNoContent {
	return &DeleteServiceProcessNoContent{}
}

/*DeleteServiceProcessNoContent handles this case with default header values.

Deleted
*/
type DeleteServiceProcessNoContent struct {
}

func (o *DeleteServiceProcessNoContent) Error() string {
	return fmt.Sprintf("[DELETE /services/{serviceId}/processes/{processId}][%d] deleteServiceProcessNoContent ", 204)
}

func (o *DeleteServiceProcessNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
