package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteServiceFilesReader is a Reader for the DeleteServiceFiles structure.
type DeleteServiceFilesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteServiceFilesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDeleteServiceFilesNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteServiceFilesNoContent creates a DeleteServiceFilesNoContent with default headers values
func NewDeleteServiceFilesNoContent() *DeleteServiceFilesNoContent {
	return &DeleteServiceFilesNoContent{}
}

/*DeleteServiceFilesNoContent handles this case with default header values.

Deleted
*/
type DeleteServiceFilesNoContent struct {
}

func (o *DeleteServiceFilesNoContent) Error() string {
	return fmt.Sprintf("[DELETE /services/{serviceId}/files][%d] deleteServiceFilesNoContent ", 204)
}

func (o *DeleteServiceFilesNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
