package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteServiceFileReader is a Reader for the DeleteServiceFile structure.
type DeleteServiceFileReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteServiceFileReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDeleteServiceFileNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteServiceFileNoContent creates a DeleteServiceFileNoContent with default headers values
func NewDeleteServiceFileNoContent() *DeleteServiceFileNoContent {
	return &DeleteServiceFileNoContent{}
}

/*DeleteServiceFileNoContent handles this case with default header values.

Deleted
*/
type DeleteServiceFileNoContent struct {
}

func (o *DeleteServiceFileNoContent) Error() string {
	return fmt.Sprintf("[DELETE /services/{serviceId}/files/{fileId}][%d] deleteServiceFileNoContent ", 204)
}

func (o *DeleteServiceFileNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
