package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteServiceProcessParams creates a new DeleteServiceProcessParams object
// with the default values initialized.
func NewDeleteServiceProcessParams() *DeleteServiceProcessParams {
	var ()
	return &DeleteServiceProcessParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteServiceProcessParamsWithTimeout creates a new DeleteServiceProcessParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteServiceProcessParamsWithTimeout(timeout time.Duration) *DeleteServiceProcessParams {
	var ()
	return &DeleteServiceProcessParams{

		timeout: timeout,
	}
}

// NewDeleteServiceProcessParamsWithContext creates a new DeleteServiceProcessParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteServiceProcessParamsWithContext(ctx context.Context) *DeleteServiceProcessParams {
	var ()
	return &DeleteServiceProcessParams{

		Context: ctx,
	}
}

/*DeleteServiceProcessParams contains all the parameters to send to the API endpoint
for the delete service process operation typically these are written to a http.Request
*/
type DeleteServiceProcessParams struct {

	/*ProcessID*/
	ProcessID string
	/*ServiceID*/
	ServiceID string

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the delete service process params
func (o *DeleteServiceProcessParams) WithTimeout(timeout time.Duration) *DeleteServiceProcessParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete service process params
func (o *DeleteServiceProcessParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete service process params
func (o *DeleteServiceProcessParams) WithContext(ctx context.Context) *DeleteServiceProcessParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete service process params
func (o *DeleteServiceProcessParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithProcessID adds the processID to the delete service process params
func (o *DeleteServiceProcessParams) WithProcessID(processID string) *DeleteServiceProcessParams {
	o.SetProcessID(processID)
	return o
}

// SetProcessID adds the processId to the delete service process params
func (o *DeleteServiceProcessParams) SetProcessID(processID string) {
	o.ProcessID = processID
}

// WithServiceID adds the serviceID to the delete service process params
func (o *DeleteServiceProcessParams) WithServiceID(serviceID string) *DeleteServiceProcessParams {
	o.SetServiceID(serviceID)
	return o
}

// SetServiceID adds the serviceId to the delete service process params
func (o *DeleteServiceProcessParams) SetServiceID(serviceID string) {
	o.ServiceID = serviceID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteServiceProcessParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param processId
	if err := r.SetPathParam("processId", o.ProcessID); err != nil {
		return err
	}

	// path param serviceId
	if err := r.SetPathParam("serviceId", o.ServiceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
