package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteServiceFileParams creates a new DeleteServiceFileParams object
// with the default values initialized.
func NewDeleteServiceFileParams() *DeleteServiceFileParams {
	var ()
	return &DeleteServiceFileParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteServiceFileParamsWithTimeout creates a new DeleteServiceFileParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteServiceFileParamsWithTimeout(timeout time.Duration) *DeleteServiceFileParams {
	var ()
	return &DeleteServiceFileParams{

		timeout: timeout,
	}
}

// NewDeleteServiceFileParamsWithContext creates a new DeleteServiceFileParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteServiceFileParamsWithContext(ctx context.Context) *DeleteServiceFileParams {
	var ()
	return &DeleteServiceFileParams{

		Context: ctx,
	}
}

/*DeleteServiceFileParams contains all the parameters to send to the API endpoint
for the delete service file operation typically these are written to a http.Request
*/
type DeleteServiceFileParams struct {

	/*FileID*/
	FileID string
	/*ServiceID*/
	ServiceID string

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the delete service file params
func (o *DeleteServiceFileParams) WithTimeout(timeout time.Duration) *DeleteServiceFileParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete service file params
func (o *DeleteServiceFileParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete service file params
func (o *DeleteServiceFileParams) WithContext(ctx context.Context) *DeleteServiceFileParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete service file params
func (o *DeleteServiceFileParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithFileID adds the fileID to the delete service file params
func (o *DeleteServiceFileParams) WithFileID(fileID string) *DeleteServiceFileParams {
	o.SetFileID(fileID)
	return o
}

// SetFileID adds the fileId to the delete service file params
func (o *DeleteServiceFileParams) SetFileID(fileID string) {
	o.FileID = fileID
}

// WithServiceID adds the serviceID to the delete service file params
func (o *DeleteServiceFileParams) WithServiceID(serviceID string) *DeleteServiceFileParams {
	o.SetServiceID(serviceID)
	return o
}

// SetServiceID adds the serviceId to the delete service file params
func (o *DeleteServiceFileParams) SetServiceID(serviceID string) {
	o.ServiceID = serviceID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteServiceFileParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param fileId
	if err := r.SetPathParam("fileId", o.FileID); err != nil {
		return err
	}

	// path param serviceId
	if err := r.SetPathParam("serviceId", o.ServiceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
