package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetProcessesParams creates a new GetProcessesParams object
// with the default values initialized.
func NewGetProcessesParams() *GetProcessesParams {

	return &GetProcessesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetProcessesParamsWithTimeout creates a new GetProcessesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetProcessesParamsWithTimeout(timeout time.Duration) *GetProcessesParams {

	return &GetProcessesParams{

		timeout: timeout,
	}
}

// NewGetProcessesParamsWithContext creates a new GetProcessesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetProcessesParamsWithContext(ctx context.Context) *GetProcessesParams {

	return &GetProcessesParams{

		Context: ctx,
	}
}

/*GetProcessesParams contains all the parameters to send to the API endpoint
for the get processes operation typically these are written to a http.Request
*/
type GetProcessesParams struct {
	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the get processes params
func (o *GetProcessesParams) WithTimeout(timeout time.Duration) *GetProcessesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get processes params
func (o *GetProcessesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get processes params
func (o *GetProcessesParams) WithContext(ctx context.Context) *GetProcessesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get processes params
func (o *GetProcessesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WriteToRequest writes these params to a swagger request
func (o *GetProcessesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
