package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetServiceParametersParams creates a new GetServiceParametersParams object
// with the default values initialized.
func NewGetServiceParametersParams() *GetServiceParametersParams {
	var ()
	return &GetServiceParametersParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetServiceParametersParamsWithTimeout creates a new GetServiceParametersParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetServiceParametersParamsWithTimeout(timeout time.Duration) *GetServiceParametersParams {
	var ()
	return &GetServiceParametersParams{

		timeout: timeout,
	}
}

// NewGetServiceParametersParamsWithContext creates a new GetServiceParametersParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetServiceParametersParamsWithContext(ctx context.Context) *GetServiceParametersParams {
	var ()
	return &GetServiceParametersParams{

		Context: ctx,
	}
}

/*GetServiceParametersParams contains all the parameters to send to the API endpoint
for the get service parameters operation typically these are written to a http.Request
*/
type GetServiceParametersParams struct {

	/*ServiceID*/
	ServiceID string

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the get service parameters params
func (o *GetServiceParametersParams) WithTimeout(timeout time.Duration) *GetServiceParametersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get service parameters params
func (o *GetServiceParametersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get service parameters params
func (o *GetServiceParametersParams) WithContext(ctx context.Context) *GetServiceParametersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get service parameters params
func (o *GetServiceParametersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithServiceID adds the serviceID to the get service parameters params
func (o *GetServiceParametersParams) WithServiceID(serviceID string) *GetServiceParametersParams {
	o.SetServiceID(serviceID)
	return o
}

// SetServiceID adds the serviceId to the get service parameters params
func (o *GetServiceParametersParams) SetServiceID(serviceID string) {
	o.ServiceID = serviceID
}

// WriteToRequest writes these params to a swagger request
func (o *GetServiceParametersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param serviceId
	if err := r.SetPathParam("serviceId", o.ServiceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
