package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetServiceFilesParams creates a new GetServiceFilesParams object
// with the default values initialized.
func NewGetServiceFilesParams() *GetServiceFilesParams {
	var ()
	return &GetServiceFilesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetServiceFilesParamsWithTimeout creates a new GetServiceFilesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetServiceFilesParamsWithTimeout(timeout time.Duration) *GetServiceFilesParams {
	var ()
	return &GetServiceFilesParams{

		timeout: timeout,
	}
}

// NewGetServiceFilesParamsWithContext creates a new GetServiceFilesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetServiceFilesParamsWithContext(ctx context.Context) *GetServiceFilesParams {
	var ()
	return &GetServiceFilesParams{

		Context: ctx,
	}
}

/*GetServiceFilesParams contains all the parameters to send to the API endpoint
for the get service files operation typically these are written to a http.Request
*/
type GetServiceFilesParams struct {

	/*ServiceID*/
	ServiceID string

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the get service files params
func (o *GetServiceFilesParams) WithTimeout(timeout time.Duration) *GetServiceFilesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get service files params
func (o *GetServiceFilesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get service files params
func (o *GetServiceFilesParams) WithContext(ctx context.Context) *GetServiceFilesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get service files params
func (o *GetServiceFilesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithServiceID adds the serviceID to the get service files params
func (o *GetServiceFilesParams) WithServiceID(serviceID string) *GetServiceFilesParams {
	o.SetServiceID(serviceID)
	return o
}

// SetServiceID adds the serviceId to the get service files params
func (o *GetServiceFilesParams) SetServiceID(serviceID string) {
	o.ServiceID = serviceID
}

// WriteToRequest writes these params to a swagger request
func (o *GetServiceFilesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param serviceId
	if err := r.SetPathParam("serviceId", o.ServiceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
