package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/SAP/cf-mta-plugin/clients/models"
)

// GetServiceParametersReader is a Reader for the GetServiceParameters structure.
type GetServiceParametersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetServiceParametersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetServiceParametersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetServiceParametersOK creates a GetServiceParametersOK with default headers values
func NewGetServiceParametersOK() *GetServiceParametersOK {
	return &GetServiceParametersOK{}
}

/*GetServiceParametersOK handles this case with default header values.

OK
*/
type GetServiceParametersOK struct {
	Payload models.Parameters
}

func (o *GetServiceParametersOK) Error() string {
	return fmt.Sprintf("[GET /services/{serviceId}/parameters][%d] getServiceParametersOK  %+v", 200, o.Payload)
}

func (o *GetServiceParametersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
