package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetProcessParams creates a new GetProcessParams object
// with the default values initialized.
func NewGetProcessParams() *GetProcessParams {
	var ()
	return &GetProcessParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetProcessParamsWithTimeout creates a new GetProcessParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetProcessParamsWithTimeout(timeout time.Duration) *GetProcessParams {
	var ()
	return &GetProcessParams{

		timeout: timeout,
	}
}

// NewGetProcessParamsWithContext creates a new GetProcessParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetProcessParamsWithContext(ctx context.Context) *GetProcessParams {
	var ()
	return &GetProcessParams{

		Context: ctx,
	}
}

/*GetProcessParams contains all the parameters to send to the API endpoint
for the get process operation typically these are written to a http.Request
*/
type GetProcessParams struct {

	/*ProcessID*/
	ProcessID string

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the get process params
func (o *GetProcessParams) WithTimeout(timeout time.Duration) *GetProcessParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get process params
func (o *GetProcessParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get process params
func (o *GetProcessParams) WithContext(ctx context.Context) *GetProcessParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get process params
func (o *GetProcessParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithProcessID adds the processID to the get process params
func (o *GetProcessParams) WithProcessID(processID string) *GetProcessParams {
	o.SetProcessID(processID)
	return o
}

// SetProcessID adds the processId to the get process params
func (o *GetProcessParams) SetProcessID(processID string) {
	o.ProcessID = processID
}

// WriteToRequest writes these params to a swagger request
func (o *GetProcessParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param processId
	if err := r.SetPathParam("processId", o.ProcessID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
