package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/SAP/cf-mta-plugin/clients/models"
)

// GetProcessServiceReader is a Reader for the GetProcessService structure.
type GetProcessServiceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetProcessServiceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetProcessServiceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetProcessServiceOK creates a GetProcessServiceOK with default headers values
func NewGetProcessServiceOK() *GetProcessServiceOK {
	return &GetProcessServiceOK{}
}

/*GetProcessServiceOK handles this case with default header values.

OK
*/
type GetProcessServiceOK struct {
	Payload *models.Service
}

func (o *GetProcessServiceOK) Error() string {
	return fmt.Sprintf("[GET /processes/{processId}/service][%d] getProcessServiceOK  %+v", 200, o.Payload)
}

func (o *GetProcessServiceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Service)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
