package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/SAP/cf-mta-plugin/clients/models"
)

// NewCreateConfigParams creates a new CreateConfigParams object
// with the default values initialized.
func NewCreateConfigParams() *CreateConfigParams {
	var ()
	return &CreateConfigParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateConfigParamsWithTimeout creates a new CreateConfigParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateConfigParamsWithTimeout(timeout time.Duration) *CreateConfigParams {
	var ()
	return &CreateConfigParams{

		timeout: timeout,
	}
}

// NewCreateConfigParamsWithContext creates a new CreateConfigParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateConfigParamsWithContext(ctx context.Context) *CreateConfigParams {
	var ()
	return &CreateConfigParams{

		Context: ctx,
	}
}

/*CreateConfigParams contains all the parameters to send to the API endpoint
for the create config operation typically these are written to a http.Request
*/
type CreateConfigParams struct {

	/*Config*/
	Config models.Config

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the create config params
func (o *CreateConfigParams) WithTimeout(timeout time.Duration) *CreateConfigParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create config params
func (o *CreateConfigParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create config params
func (o *CreateConfigParams) WithContext(ctx context.Context) *CreateConfigParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create config params
func (o *CreateConfigParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithConfig adds the config to the create config params
func (o *CreateConfigParams) WithConfig(config models.Config) *CreateConfigParams {
	o.SetConfig(config)
	return o
}

// SetConfig adds the config to the create config params
func (o *CreateConfigParams) SetConfig(config models.Config) {
	o.Config = config
}

// WriteToRequest writes these params to a swagger request
func (o *CreateConfigParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if err := r.SetBodyParam(o.Config); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
