package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/SAP/cf-mta-plugin/clients/models"
)

// CreateConfigReader is a Reader for the CreateConfig structure.
type CreateConfigReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateConfigReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCreateConfigOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateConfigOK creates a CreateConfigOK with default headers values
func NewCreateConfigOK() *CreateConfigOK {
	return &CreateConfigOK{}
}

/*CreateConfigOK handles this case with default header values.

Created
*/
type CreateConfigOK struct {
	Payload models.Config
}

func (o *CreateConfigOK) Error() string {
	return fmt.Sprintf("[POST /config][%d] createConfigOK  %+v", 200, o.Payload)
}

func (o *CreateConfigOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
