package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/SAP/cf-mta-plugin/clients/models"
)

// NewCreateBreakpointsParams creates a new CreateBreakpointsParams object
// with the default values initialized.
func NewCreateBreakpointsParams() *CreateBreakpointsParams {
	var ()
	return &CreateBreakpointsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateBreakpointsParamsWithTimeout creates a new CreateBreakpointsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateBreakpointsParamsWithTimeout(timeout time.Duration) *CreateBreakpointsParams {
	var ()
	return &CreateBreakpointsParams{

		timeout: timeout,
	}
}

// NewCreateBreakpointsParamsWithContext creates a new CreateBreakpointsParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateBreakpointsParamsWithContext(ctx context.Context) *CreateBreakpointsParams {
	var ()
	return &CreateBreakpointsParams{

		Context: ctx,
	}
}

/*CreateBreakpointsParams contains all the parameters to send to the API endpoint
for the create breakpoints operation typically these are written to a http.Request
*/
type CreateBreakpointsParams struct {

	/*Breakpoints*/
	Breakpoints models.Breakpoints

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the create breakpoints params
func (o *CreateBreakpointsParams) WithTimeout(timeout time.Duration) *CreateBreakpointsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create breakpoints params
func (o *CreateBreakpointsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create breakpoints params
func (o *CreateBreakpointsParams) WithContext(ctx context.Context) *CreateBreakpointsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create breakpoints params
func (o *CreateBreakpointsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithBreakpoints adds the breakpoints to the create breakpoints params
func (o *CreateBreakpointsParams) WithBreakpoints(breakpoints models.Breakpoints) *CreateBreakpointsParams {
	o.SetBreakpoints(breakpoints)
	return o
}

// SetBreakpoints adds the breakpoints to the create breakpoints params
func (o *CreateBreakpointsParams) SetBreakpoints(breakpoints models.Breakpoints) {
	o.Breakpoints = breakpoints
}

// WriteToRequest writes these params to a swagger request
func (o *CreateBreakpointsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if err := r.SetBodyParam(o.Breakpoints); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
