// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewExecuteActionParams creates a new ExecuteActionParams object
// with the default values initialized.
func NewExecuteActionParams() *ExecuteActionParams {
	var ()
	return &ExecuteActionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewExecuteActionParamsWithTimeout creates a new ExecuteActionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewExecuteActionParamsWithTimeout(timeout time.Duration) *ExecuteActionParams {
	var ()
	return &ExecuteActionParams{

		timeout: timeout,
	}
}

// NewExecuteActionParamsWithContext creates a new ExecuteActionParams object
// with the default values initialized, and the ability to set a context for a request
func NewExecuteActionParamsWithContext(ctx context.Context) *ExecuteActionParams {
	var ()
	return &ExecuteActionParams{

		Context: ctx,
	}
}

// NewExecuteActionParamsWithHTTPClient creates a new ExecuteActionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewExecuteActionParamsWithHTTPClient(client *http.Client) *ExecuteActionParams {
	var ()
	return &ExecuteActionParams{
		HTTPClient: client,
	}
}

/*ExecuteActionParams contains all the parameters to send to the API endpoint
for the execute action operation typically these are written to a http.Request
*/
type ExecuteActionParams struct {

	/*ActionID*/
	ActionID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the execute action params
func (o *ExecuteActionParams) WithTimeout(timeout time.Duration) *ExecuteActionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the execute action params
func (o *ExecuteActionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the execute action params
func (o *ExecuteActionParams) WithContext(ctx context.Context) *ExecuteActionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the execute action params
func (o *ExecuteActionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the execute action params
func (o *ExecuteActionParams) WithHTTPClient(client *http.Client) *ExecuteActionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the execute action params
func (o *ExecuteActionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithActionID adds the actionID to the execute action params
func (o *ExecuteActionParams) WithActionID(actionID string) *ExecuteActionParams {
	o.SetActionID(actionID)
	return o
}

// SetActionID adds the actionId to the execute action params
func (o *ExecuteActionParams) SetActionID(actionID string) {
	o.ActionID = actionID
}

// WriteToRequest writes these params to a swagger request
func (o *ExecuteActionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param actionId
	if err := r.SetPathParam("actionId", o.ActionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
