package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetMonitorParams creates a new GetMonitorParams object
// with the default values initialized.
func NewGetMonitorParams() *GetMonitorParams {

	return &GetMonitorParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetMonitorParamsWithTimeout creates a new GetMonitorParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetMonitorParamsWithTimeout(timeout time.Duration) *GetMonitorParams {

	return &GetMonitorParams{

		timeout: timeout,
	}
}

// NewGetMonitorParamsWithContext creates a new GetMonitorParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetMonitorParamsWithContext(ctx context.Context) *GetMonitorParams {

	return &GetMonitorParams{

		Context: ctx,
	}
}

/*GetMonitorParams contains all the parameters to send to the API endpoint
for the get monitor operation typically these are written to a http.Request
*/
type GetMonitorParams struct {
	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the get monitor params
func (o *GetMonitorParams) WithTimeout(timeout time.Duration) *GetMonitorParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get monitor params
func (o *GetMonitorParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get monitor params
func (o *GetMonitorParams) WithContext(ctx context.Context) *GetMonitorParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get monitor params
func (o *GetMonitorParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WriteToRequest writes these params to a swagger request
func (o *GetMonitorParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
