package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetRoadmapTaskErrorParams creates a new GetRoadmapTaskErrorParams object
// with the default values initialized.
func NewGetRoadmapTaskErrorParams() *GetRoadmapTaskErrorParams {
	var ()
	return &GetRoadmapTaskErrorParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetRoadmapTaskErrorParamsWithTimeout creates a new GetRoadmapTaskErrorParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetRoadmapTaskErrorParamsWithTimeout(timeout time.Duration) *GetRoadmapTaskErrorParams {
	var ()
	return &GetRoadmapTaskErrorParams{

		timeout: timeout,
	}
}

// NewGetRoadmapTaskErrorParamsWithContext creates a new GetRoadmapTaskErrorParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetRoadmapTaskErrorParamsWithContext(ctx context.Context) *GetRoadmapTaskErrorParams {
	var ()
	return &GetRoadmapTaskErrorParams{

		Context: ctx,
	}
}

/*GetRoadmapTaskErrorParams contains all the parameters to send to the API endpoint
for the get roadmap task error operation typically these are written to a http.Request
*/
type GetRoadmapTaskErrorParams struct {

	/*TaskID*/
	TaskID string

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the get roadmap task error params
func (o *GetRoadmapTaskErrorParams) WithTimeout(timeout time.Duration) *GetRoadmapTaskErrorParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get roadmap task error params
func (o *GetRoadmapTaskErrorParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get roadmap task error params
func (o *GetRoadmapTaskErrorParams) WithContext(ctx context.Context) *GetRoadmapTaskErrorParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get roadmap task error params
func (o *GetRoadmapTaskErrorParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithTaskID adds the taskID to the get roadmap task error params
func (o *GetRoadmapTaskErrorParams) WithTaskID(taskID string) *GetRoadmapTaskErrorParams {
	o.SetTaskID(taskID)
	return o
}

// SetTaskID adds the taskId to the get roadmap task error params
func (o *GetRoadmapTaskErrorParams) SetTaskID(taskID string) {
	o.TaskID = taskID
}

// WriteToRequest writes these params to a swagger request
func (o *GetRoadmapTaskErrorParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param taskId
	if err := r.SetPathParam("taskId", o.TaskID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
