package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/SAP/cf-mta-plugin/clients/models"
)

// GetPropertyReader is a Reader for the GetProperty structure.
type GetPropertyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPropertyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetPropertyOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetPropertyOK creates a GetPropertyOK with default headers values
func NewGetPropertyOK() *GetPropertyOK {
	return &GetPropertyOK{}
}

/*GetPropertyOK handles this case with default header values.

OK
*/
type GetPropertyOK struct {
	Payload *models.Property
}

func (o *GetPropertyOK) Error() string {
	return fmt.Sprintf("[GET /properties/{propertyId}][%d] getPropertyOK  %+v", 200, o.Payload)
}

func (o *GetPropertyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Property)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
