package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetMetaDialogsParams creates a new GetMetaDialogsParams object
// with the default values initialized.
func NewGetMetaDialogsParams() *GetMetaDialogsParams {
	var ()
	return &GetMetaDialogsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetMetaDialogsParamsWithTimeout creates a new GetMetaDialogsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetMetaDialogsParamsWithTimeout(timeout time.Duration) *GetMetaDialogsParams {
	var ()
	return &GetMetaDialogsParams{

		timeout: timeout,
	}
}

// NewGetMetaDialogsParamsWithContext creates a new GetMetaDialogsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetMetaDialogsParamsWithContext(ctx context.Context) *GetMetaDialogsParams {
	var ()
	return &GetMetaDialogsParams{

		Context: ctx,
	}
}

/*GetMetaDialogsParams contains all the parameters to send to the API endpoint
for the get meta dialogs operation typically these are written to a http.Request
*/
type GetMetaDialogsParams struct {

	/*MetaDialogURL*/
	MetaDialogURL string

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the get meta dialogs params
func (o *GetMetaDialogsParams) WithTimeout(timeout time.Duration) *GetMetaDialogsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get meta dialogs params
func (o *GetMetaDialogsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get meta dialogs params
func (o *GetMetaDialogsParams) WithContext(ctx context.Context) *GetMetaDialogsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get meta dialogs params
func (o *GetMetaDialogsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithMetaDialogURL adds the metaDialogURL to the get meta dialogs params
func (o *GetMetaDialogsParams) WithMetaDialogURL(metaDialogURL string) *GetMetaDialogsParams {
	o.SetMetaDialogURL(metaDialogURL)
	return o
}

// SetMetaDialogURL adds the metaDialogUrl to the get meta dialogs params
func (o *GetMetaDialogsParams) SetMetaDialogURL(metaDialogURL string) {
	o.MetaDialogURL = metaDialogURL
}

// WriteToRequest writes these params to a swagger request
func (o *GetMetaDialogsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param metaDialogURL
	if err := r.SetPathParam("metaDialogURL", o.MetaDialogURL); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
