// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetTasklistParams creates a new GetTasklistParams object
// with the default values initialized.
func NewGetTasklistParams() *GetTasklistParams {

	return &GetTasklistParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetTasklistParamsWithTimeout creates a new GetTasklistParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetTasklistParamsWithTimeout(timeout time.Duration) *GetTasklistParams {

	return &GetTasklistParams{

		timeout: timeout,
	}
}

// NewGetTasklistParamsWithContext creates a new GetTasklistParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetTasklistParamsWithContext(ctx context.Context) *GetTasklistParams {

	return &GetTasklistParams{

		Context: ctx,
	}
}

// NewGetTasklistParamsWithHTTPClient creates a new GetTasklistParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetTasklistParamsWithHTTPClient(client *http.Client) *GetTasklistParams {

	return &GetTasklistParams{
		HTTPClient: client,
	}
}

/*GetTasklistParams contains all the parameters to send to the API endpoint
for the get tasklist operation typically these are written to a http.Request
*/
type GetTasklistParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get tasklist params
func (o *GetTasklistParams) WithTimeout(timeout time.Duration) *GetTasklistParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get tasklist params
func (o *GetTasklistParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get tasklist params
func (o *GetTasklistParams) WithContext(ctx context.Context) *GetTasklistParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get tasklist params
func (o *GetTasklistParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get tasklist params
func (o *GetTasklistParams) WithHTTPClient(client *http.Client) *GetTasklistParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get tasklist params
func (o *GetTasklistParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetTasklistParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
