package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetRoadmapTaskParams creates a new GetRoadmapTaskParams object
// with the default values initialized.
func NewGetRoadmapTaskParams() *GetRoadmapTaskParams {
	var ()
	return &GetRoadmapTaskParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetRoadmapTaskParamsWithTimeout creates a new GetRoadmapTaskParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetRoadmapTaskParamsWithTimeout(timeout time.Duration) *GetRoadmapTaskParams {
	var ()
	return &GetRoadmapTaskParams{

		timeout: timeout,
	}
}

// NewGetRoadmapTaskParamsWithContext creates a new GetRoadmapTaskParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetRoadmapTaskParamsWithContext(ctx context.Context) *GetRoadmapTaskParams {
	var ()
	return &GetRoadmapTaskParams{

		Context: ctx,
	}
}

/*GetRoadmapTaskParams contains all the parameters to send to the API endpoint
for the get roadmap task operation typically these are written to a http.Request
*/
type GetRoadmapTaskParams struct {

	/*TaskID*/
	TaskID string

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the get roadmap task params
func (o *GetRoadmapTaskParams) WithTimeout(timeout time.Duration) *GetRoadmapTaskParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get roadmap task params
func (o *GetRoadmapTaskParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get roadmap task params
func (o *GetRoadmapTaskParams) WithContext(ctx context.Context) *GetRoadmapTaskParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get roadmap task params
func (o *GetRoadmapTaskParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithTaskID adds the taskID to the get roadmap task params
func (o *GetRoadmapTaskParams) WithTaskID(taskID string) *GetRoadmapTaskParams {
	o.SetTaskID(taskID)
	return o
}

// SetTaskID adds the taskId to the get roadmap task params
func (o *GetRoadmapTaskParams) SetTaskID(taskID string) {
	o.TaskID = taskID
}

// WriteToRequest writes these params to a swagger request
func (o *GetRoadmapTaskParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param taskId
	if err := r.SetPathParam("taskId", o.TaskID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
