package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetBreakpointParams creates a new GetBreakpointParams object
// with the default values initialized.
func NewGetBreakpointParams() *GetBreakpointParams {
	var ()
	return &GetBreakpointParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetBreakpointParamsWithTimeout creates a new GetBreakpointParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetBreakpointParamsWithTimeout(timeout time.Duration) *GetBreakpointParams {
	var ()
	return &GetBreakpointParams{

		timeout: timeout,
	}
}

// NewGetBreakpointParamsWithContext creates a new GetBreakpointParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetBreakpointParamsWithContext(ctx context.Context) *GetBreakpointParams {
	var ()
	return &GetBreakpointParams{

		Context: ctx,
	}
}

/*GetBreakpointParams contains all the parameters to send to the API endpoint
for the get breakpoint operation typically these are written to a http.Request
*/
type GetBreakpointParams struct {

	/*BreakpointID*/
	BreakpointID string

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the get breakpoint params
func (o *GetBreakpointParams) WithTimeout(timeout time.Duration) *GetBreakpointParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get breakpoint params
func (o *GetBreakpointParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get breakpoint params
func (o *GetBreakpointParams) WithContext(ctx context.Context) *GetBreakpointParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get breakpoint params
func (o *GetBreakpointParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithBreakpointID adds the breakpointID to the get breakpoint params
func (o *GetBreakpointParams) WithBreakpointID(breakpointID string) *GetBreakpointParams {
	o.SetBreakpointID(breakpointID)
	return o
}

// SetBreakpointID adds the breakpointId to the get breakpoint params
func (o *GetBreakpointParams) SetBreakpointID(breakpointID string) {
	o.BreakpointID = breakpointID
}

// WriteToRequest writes these params to a swagger request
func (o *GetBreakpointParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param breakpointId
	if err := r.SetPathParam("breakpointId", o.BreakpointID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
