// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/SAP/cf-mta-plugin/clients/models"
)

// GetTasklistTaskErrorReader is a Reader for the GetTasklistTaskError structure.
type GetTasklistTaskErrorReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetTasklistTaskErrorReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetTasklistTaskErrorOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetTasklistTaskErrorOK creates a GetTasklistTaskErrorOK with default headers values
func NewGetTasklistTaskErrorOK() *GetTasklistTaskErrorOK {
	return &GetTasklistTaskErrorOK{}
}

/*GetTasklistTaskErrorOK handles this case with default header values.

OK
*/
type GetTasklistTaskErrorOK struct {
	Payload *models.Error
}

func (o *GetTasklistTaskErrorOK) Error() string {
	return fmt.Sprintf("[GET /tasklist/{taskId}/error][%d] getTasklistTaskErrorOK  %+v", 200, o.Payload)
}

func (o *GetTasklistTaskErrorOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
