// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetLogContentReader is a Reader for the GetLogContent structure.
type GetLogContentReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetLogContentReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetLogContentOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetLogContentOK creates a GetLogContentOK with default headers values
func NewGetLogContentOK() *GetLogContentOK {
	return &GetLogContentOK{}
}

/*GetLogContentOK handles this case with default header values.

OK
*/
type GetLogContentOK struct {
	Payload string
}

func (o *GetLogContentOK) Error() string {
	return fmt.Sprintf("[GET /logs/{logId}/content][%d] getLogContentOK  %+v", 200, o.Payload)
}

func (o *GetLogContentOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
