package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/SAP/cf-mta-plugin/clients/models"
)

// GetBreakpointsReader is a Reader for the GetBreakpoints structure.
type GetBreakpointsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetBreakpointsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetBreakpointsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetBreakpointsOK creates a GetBreakpointsOK with default headers values
func NewGetBreakpointsOK() *GetBreakpointsOK {
	return &GetBreakpointsOK{}
}

/*GetBreakpointsOK handles this case with default header values.

OK
*/
type GetBreakpointsOK struct {
	Payload models.Breakpoints
}

func (o *GetBreakpointsOK) Error() string {
	return fmt.Sprintf("[GET /breakpoints][%d] getBreakpointsOK  %+v", 200, o.Payload)
}

func (o *GetBreakpointsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
