package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/SAP/cf-mta-plugin/clients/models"
)

// GetCurrentBreakpointReader is a Reader for the GetCurrentBreakpoint structure.
type GetCurrentBreakpointReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCurrentBreakpointReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetCurrentBreakpointOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetCurrentBreakpointOK creates a GetCurrentBreakpointOK with default headers values
func NewGetCurrentBreakpointOK() *GetCurrentBreakpointOK {
	return &GetCurrentBreakpointOK{}
}

/*GetCurrentBreakpointOK handles this case with default header values.

OK
*/
type GetCurrentBreakpointOK struct {
	Payload *models.Breakpoint
}

func (o *GetCurrentBreakpointOK) Error() string {
	return fmt.Sprintf("[GET /currentBreakpoints/{currentBreakpointId}][%d] getCurrentBreakpointOK  %+v", 200, o.Payload)
}

func (o *GetCurrentBreakpointOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Breakpoint)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
