package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetMonitorTaskLogsParams creates a new GetMonitorTaskLogsParams object
// with the default values initialized.
func NewGetMonitorTaskLogsParams() *GetMonitorTaskLogsParams {
	var ()
	return &GetMonitorTaskLogsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetMonitorTaskLogsParamsWithTimeout creates a new GetMonitorTaskLogsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetMonitorTaskLogsParamsWithTimeout(timeout time.Duration) *GetMonitorTaskLogsParams {
	var ()
	return &GetMonitorTaskLogsParams{

		timeout: timeout,
	}
}

// NewGetMonitorTaskLogsParamsWithContext creates a new GetMonitorTaskLogsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetMonitorTaskLogsParamsWithContext(ctx context.Context) *GetMonitorTaskLogsParams {
	var ()
	return &GetMonitorTaskLogsParams{

		Context: ctx,
	}
}

/*GetMonitorTaskLogsParams contains all the parameters to send to the API endpoint
for the get monitor task logs operation typically these are written to a http.Request
*/
type GetMonitorTaskLogsParams struct {

	/*TaskID*/
	TaskID string

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the get monitor task logs params
func (o *GetMonitorTaskLogsParams) WithTimeout(timeout time.Duration) *GetMonitorTaskLogsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get monitor task logs params
func (o *GetMonitorTaskLogsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get monitor task logs params
func (o *GetMonitorTaskLogsParams) WithContext(ctx context.Context) *GetMonitorTaskLogsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get monitor task logs params
func (o *GetMonitorTaskLogsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithTaskID adds the taskID to the get monitor task logs params
func (o *GetMonitorTaskLogsParams) WithTaskID(taskID string) *GetMonitorTaskLogsParams {
	o.SetTaskID(taskID)
	return o
}

// SetTaskID adds the taskId to the get monitor task logs params
func (o *GetMonitorTaskLogsParams) SetTaskID(taskID string) {
	o.TaskID = taskID
}

// WriteToRequest writes these params to a swagger request
func (o *GetMonitorTaskLogsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param taskId
	if err := r.SetPathParam("taskId", o.TaskID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
