package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/SAP/cf-mta-plugin/clients/models"
)

// GetDialogReader is a Reader for the GetDialog structure.
type GetDialogReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDialogReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetDialogOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetDialogOK creates a GetDialogOK with default headers values
func NewGetDialogOK() *GetDialogOK {
	return &GetDialogOK{}
}

/*GetDialogOK handles this case with default header values.

OK
*/
type GetDialogOK struct {
	Payload *models.Dialog
}

func (o *GetDialogOK) Error() string {
	return fmt.Sprintf("[GET /dialogs/{dialogId}][%d] getDialogOK  %+v", 200, o.Payload)
}

func (o *GetDialogOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Dialog)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
