package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetCurrentBreakpointParams creates a new GetCurrentBreakpointParams object
// with the default values initialized.
func NewGetCurrentBreakpointParams() *GetCurrentBreakpointParams {
	var ()
	return &GetCurrentBreakpointParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetCurrentBreakpointParamsWithTimeout creates a new GetCurrentBreakpointParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetCurrentBreakpointParamsWithTimeout(timeout time.Duration) *GetCurrentBreakpointParams {
	var ()
	return &GetCurrentBreakpointParams{

		timeout: timeout,
	}
}

// NewGetCurrentBreakpointParamsWithContext creates a new GetCurrentBreakpointParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetCurrentBreakpointParamsWithContext(ctx context.Context) *GetCurrentBreakpointParams {
	var ()
	return &GetCurrentBreakpointParams{

		Context: ctx,
	}
}

/*GetCurrentBreakpointParams contains all the parameters to send to the API endpoint
for the get current breakpoint operation typically these are written to a http.Request
*/
type GetCurrentBreakpointParams struct {

	/*CurrentBreakpointID*/
	CurrentBreakpointID string

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the get current breakpoint params
func (o *GetCurrentBreakpointParams) WithTimeout(timeout time.Duration) *GetCurrentBreakpointParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get current breakpoint params
func (o *GetCurrentBreakpointParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get current breakpoint params
func (o *GetCurrentBreakpointParams) WithContext(ctx context.Context) *GetCurrentBreakpointParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get current breakpoint params
func (o *GetCurrentBreakpointParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithCurrentBreakpointID adds the currentBreakpointID to the get current breakpoint params
func (o *GetCurrentBreakpointParams) WithCurrentBreakpointID(currentBreakpointID string) *GetCurrentBreakpointParams {
	o.SetCurrentBreakpointID(currentBreakpointID)
	return o
}

// SetCurrentBreakpointID adds the currentBreakpointId to the get current breakpoint params
func (o *GetCurrentBreakpointParams) SetCurrentBreakpointID(currentBreakpointID string) {
	o.CurrentBreakpointID = currentBreakpointID
}

// WriteToRequest writes these params to a swagger request
func (o *GetCurrentBreakpointParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param currentBreakpointId
	if err := r.SetPathParam("currentBreakpointId", o.CurrentBreakpointID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
