package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetPropertyParams creates a new GetPropertyParams object
// with the default values initialized.
func NewGetPropertyParams() *GetPropertyParams {
	var ()
	return &GetPropertyParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetPropertyParamsWithTimeout creates a new GetPropertyParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetPropertyParamsWithTimeout(timeout time.Duration) *GetPropertyParams {
	var ()
	return &GetPropertyParams{

		timeout: timeout,
	}
}

// NewGetPropertyParamsWithContext creates a new GetPropertyParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetPropertyParamsWithContext(ctx context.Context) *GetPropertyParams {
	var ()
	return &GetPropertyParams{

		Context: ctx,
	}
}

/*GetPropertyParams contains all the parameters to send to the API endpoint
for the get property operation typically these are written to a http.Request
*/
type GetPropertyParams struct {

	/*PropertyID*/
	PropertyID string

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the get property params
func (o *GetPropertyParams) WithTimeout(timeout time.Duration) *GetPropertyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get property params
func (o *GetPropertyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get property params
func (o *GetPropertyParams) WithContext(ctx context.Context) *GetPropertyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get property params
func (o *GetPropertyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithPropertyID adds the propertyID to the get property params
func (o *GetPropertyParams) WithPropertyID(propertyID string) *GetPropertyParams {
	o.SetPropertyID(propertyID)
	return o
}

// SetPropertyID adds the propertyId to the get property params
func (o *GetPropertyParams) SetPropertyID(propertyID string) {
	o.PropertyID = propertyID
}

// WriteToRequest writes these params to a swagger request
func (o *GetPropertyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param propertyId
	if err := r.SetPathParam("propertyId", o.PropertyID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
