package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetDialogsParams creates a new GetDialogsParams object
// with the default values initialized.
func NewGetDialogsParams() *GetDialogsParams {

	return &GetDialogsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetDialogsParamsWithTimeout creates a new GetDialogsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetDialogsParamsWithTimeout(timeout time.Duration) *GetDialogsParams {

	return &GetDialogsParams{

		timeout: timeout,
	}
}

// NewGetDialogsParamsWithContext creates a new GetDialogsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetDialogsParamsWithContext(ctx context.Context) *GetDialogsParams {

	return &GetDialogsParams{

		Context: ctx,
	}
}

/*GetDialogsParams contains all the parameters to send to the API endpoint
for the get dialogs operation typically these are written to a http.Request
*/
type GetDialogsParams struct {
	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the get dialogs params
func (o *GetDialogsParams) WithTimeout(timeout time.Duration) *GetDialogsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get dialogs params
func (o *GetDialogsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get dialogs params
func (o *GetDialogsParams) WithContext(ctx context.Context) *GetDialogsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get dialogs params
func (o *GetDialogsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WriteToRequest writes these params to a swagger request
func (o *GetDialogsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
