package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetMonitorTaskParams creates a new GetMonitorTaskParams object
// with the default values initialized.
func NewGetMonitorTaskParams() *GetMonitorTaskParams {
	var ()
	return &GetMonitorTaskParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetMonitorTaskParamsWithTimeout creates a new GetMonitorTaskParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetMonitorTaskParamsWithTimeout(timeout time.Duration) *GetMonitorTaskParams {
	var ()
	return &GetMonitorTaskParams{

		timeout: timeout,
	}
}

// NewGetMonitorTaskParamsWithContext creates a new GetMonitorTaskParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetMonitorTaskParamsWithContext(ctx context.Context) *GetMonitorTaskParams {
	var ()
	return &GetMonitorTaskParams{

		Context: ctx,
	}
}

/*GetMonitorTaskParams contains all the parameters to send to the API endpoint
for the get monitor task operation typically these are written to a http.Request
*/
type GetMonitorTaskParams struct {

	/*TaskID*/
	TaskID string

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the get monitor task params
func (o *GetMonitorTaskParams) WithTimeout(timeout time.Duration) *GetMonitorTaskParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get monitor task params
func (o *GetMonitorTaskParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get monitor task params
func (o *GetMonitorTaskParams) WithContext(ctx context.Context) *GetMonitorTaskParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get monitor task params
func (o *GetMonitorTaskParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithTaskID adds the taskID to the get monitor task params
func (o *GetMonitorTaskParams) WithTaskID(taskID string) *GetMonitorTaskParams {
	o.SetTaskID(taskID)
	return o
}

// SetTaskID adds the taskId to the get monitor task params
func (o *GetMonitorTaskParams) SetTaskID(taskID string) {
	o.TaskID = taskID
}

// WriteToRequest writes these params to a swagger request
func (o *GetMonitorTaskParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param taskId
	if err := r.SetPathParam("taskId", o.TaskID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
