// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetTasklistTaskErrorParams creates a new GetTasklistTaskErrorParams object
// with the default values initialized.
func NewGetTasklistTaskErrorParams() *GetTasklistTaskErrorParams {
	var ()
	return &GetTasklistTaskErrorParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetTasklistTaskErrorParamsWithTimeout creates a new GetTasklistTaskErrorParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetTasklistTaskErrorParamsWithTimeout(timeout time.Duration) *GetTasklistTaskErrorParams {
	var ()
	return &GetTasklistTaskErrorParams{

		timeout: timeout,
	}
}

// NewGetTasklistTaskErrorParamsWithContext creates a new GetTasklistTaskErrorParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetTasklistTaskErrorParamsWithContext(ctx context.Context) *GetTasklistTaskErrorParams {
	var ()
	return &GetTasklistTaskErrorParams{

		Context: ctx,
	}
}

// NewGetTasklistTaskErrorParamsWithHTTPClient creates a new GetTasklistTaskErrorParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetTasklistTaskErrorParamsWithHTTPClient(client *http.Client) *GetTasklistTaskErrorParams {
	var ()
	return &GetTasklistTaskErrorParams{
		HTTPClient: client,
	}
}

/*GetTasklistTaskErrorParams contains all the parameters to send to the API endpoint
for the get tasklist task error operation typically these are written to a http.Request
*/
type GetTasklistTaskErrorParams struct {

	/*TaskID*/
	TaskID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get tasklist task error params
func (o *GetTasklistTaskErrorParams) WithTimeout(timeout time.Duration) *GetTasklistTaskErrorParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get tasklist task error params
func (o *GetTasklistTaskErrorParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get tasklist task error params
func (o *GetTasklistTaskErrorParams) WithContext(ctx context.Context) *GetTasklistTaskErrorParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get tasklist task error params
func (o *GetTasklistTaskErrorParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get tasklist task error params
func (o *GetTasklistTaskErrorParams) WithHTTPClient(client *http.Client) *GetTasklistTaskErrorParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get tasklist task error params
func (o *GetTasklistTaskErrorParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTaskID adds the taskID to the get tasklist task error params
func (o *GetTasklistTaskErrorParams) WithTaskID(taskID string) *GetTasklistTaskErrorParams {
	o.SetTaskID(taskID)
	return o
}

// SetTaskID adds the taskId to the get tasklist task error params
func (o *GetTasklistTaskErrorParams) SetTaskID(taskID string) {
	o.TaskID = taskID
}

// WriteToRequest writes these params to a swagger request
func (o *GetTasklistTaskErrorParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param taskId
	if err := r.SetPathParam("taskId", o.TaskID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
