// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetActionsParams creates a new GetActionsParams object
// with the default values initialized.
func NewGetActionsParams() *GetActionsParams {

	return &GetActionsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetActionsParamsWithTimeout creates a new GetActionsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetActionsParamsWithTimeout(timeout time.Duration) *GetActionsParams {

	return &GetActionsParams{

		timeout: timeout,
	}
}

// NewGetActionsParamsWithContext creates a new GetActionsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetActionsParamsWithContext(ctx context.Context) *GetActionsParams {

	return &GetActionsParams{

		Context: ctx,
	}
}

// NewGetActionsParamsWithHTTPClient creates a new GetActionsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetActionsParamsWithHTTPClient(client *http.Client) *GetActionsParams {

	return &GetActionsParams{
		HTTPClient: client,
	}
}

/*GetActionsParams contains all the parameters to send to the API endpoint
for the get actions operation typically these are written to a http.Request
*/
type GetActionsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get actions params
func (o *GetActionsParams) WithTimeout(timeout time.Duration) *GetActionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get actions params
func (o *GetActionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get actions params
func (o *GetActionsParams) WithContext(ctx context.Context) *GetActionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get actions params
func (o *GetActionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get actions params
func (o *GetActionsParams) WithHTTPClient(client *http.Client) *GetActionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get actions params
func (o *GetActionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetActionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
