package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetPropertiesParams creates a new GetPropertiesParams object
// with the default values initialized.
func NewGetPropertiesParams() *GetPropertiesParams {

	return &GetPropertiesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetPropertiesParamsWithTimeout creates a new GetPropertiesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetPropertiesParamsWithTimeout(timeout time.Duration) *GetPropertiesParams {

	return &GetPropertiesParams{

		timeout: timeout,
	}
}

// NewGetPropertiesParamsWithContext creates a new GetPropertiesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetPropertiesParamsWithContext(ctx context.Context) *GetPropertiesParams {

	return &GetPropertiesParams{

		Context: ctx,
	}
}

/*GetPropertiesParams contains all the parameters to send to the API endpoint
for the get properties operation typically these are written to a http.Request
*/
type GetPropertiesParams struct {
	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the get properties params
func (o *GetPropertiesParams) WithTimeout(timeout time.Duration) *GetPropertiesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get properties params
func (o *GetPropertiesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get properties params
func (o *GetPropertiesParams) WithContext(ctx context.Context) *GetPropertiesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get properties params
func (o *GetPropertiesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WriteToRequest writes these params to a swagger request
func (o *GetPropertiesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
