// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/SAP/cf-mta-plugin/clients/models"
)

// GetTasklistTaskLogsReader is a Reader for the GetTasklistTaskLogs structure.
type GetTasklistTaskLogsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetTasklistTaskLogsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetTasklistTaskLogsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetTasklistTaskLogsOK creates a GetTasklistTaskLogsOK with default headers values
func NewGetTasklistTaskLogsOK() *GetTasklistTaskLogsOK {
	return &GetTasklistTaskLogsOK{}
}

/*GetTasklistTaskLogsOK handles this case with default header values.

OK
*/
type GetTasklistTaskLogsOK struct {
	Payload models.Logs
}

func (o *GetTasklistTaskLogsOK) Error() string {
	return fmt.Sprintf("[GET /tasklist/{taskId}/logs][%d] getTasklistTaskLogsOK  %+v", 200, o.Payload)
}

func (o *GetTasklistTaskLogsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
