// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetLogParams creates a new GetLogParams object
// with the default values initialized.
func NewGetLogParams() *GetLogParams {
	var ()
	return &GetLogParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetLogParamsWithTimeout creates a new GetLogParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetLogParamsWithTimeout(timeout time.Duration) *GetLogParams {
	var ()
	return &GetLogParams{

		timeout: timeout,
	}
}

// NewGetLogParamsWithContext creates a new GetLogParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetLogParamsWithContext(ctx context.Context) *GetLogParams {
	var ()
	return &GetLogParams{

		Context: ctx,
	}
}

// NewGetLogParamsWithHTTPClient creates a new GetLogParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetLogParamsWithHTTPClient(client *http.Client) *GetLogParams {
	var ()
	return &GetLogParams{
		HTTPClient: client,
	}
}

/*GetLogParams contains all the parameters to send to the API endpoint
for the get log operation typically these are written to a http.Request
*/
type GetLogParams struct {

	/*LogID*/
	LogID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get log params
func (o *GetLogParams) WithTimeout(timeout time.Duration) *GetLogParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get log params
func (o *GetLogParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get log params
func (o *GetLogParams) WithContext(ctx context.Context) *GetLogParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get log params
func (o *GetLogParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get log params
func (o *GetLogParams) WithHTTPClient(client *http.Client) *GetLogParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get log params
func (o *GetLogParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLogID adds the logID to the get log params
func (o *GetLogParams) WithLogID(logID string) *GetLogParams {
	o.SetLogID(logID)
	return o
}

// SetLogID adds the logId to the get log params
func (o *GetLogParams) SetLogID(logID string) {
	o.LogID = logID
}

// WriteToRequest writes these params to a swagger request
func (o *GetLogParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param logId
	if err := r.SetPathParam("logId", o.LogID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
