name: Multiapps CLI Plugin build

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'

    - name: Download dependencies
      run: go get -d -t ./...

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
